In [1]:
import torch

1. Multiple views of storage

In [8]:
m = torch.full((13,13), 1)#### Generating a matrix
m

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
index = torch.tensor([1,6,11])
m1 = m.index_fill_(0,index, 2)
m1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

In [25]:
indices = (torch.LongTensor([3, 4, 8, 9, 8, 9, 3, 4, 3, 3, 4, 4, 8, 8, 9, 9]),
           torch.LongTensor([3, 4, 8, 9, 3, 4, 8, 9, 4, 9, 3, 8, 4, 9, 3, 8]))
value = torch.tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
m2 = m1.index_put_(indices, value)
m2

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

2. Eigen decomposition 

In [132]:
M = torch.empty((20,20)).normal_() ##Matrix with gaussian coefficients

a = torch.arange(1,21,dtype=torch.float)
D = torch.diag(a) ##Diagonal matrix

M_inv = torch.inverse(M) ## Inverse of matrix M

MD = torch.mm(D,M) ## Product of Diagonal matrix and matrix M
MM = torch.mm(M_inv,MD) ## Product of inverse matrix and MD

eigenvalues = torch.eig(MM,eigenvectors=False)
eigenvalues

torch.return_types.eig(
eigenvalues=tensor([[20.0000,  0.0000],
        [ 1.0000,  0.0000],
        [19.0000,  0.0000],
        [ 2.0000,  0.0000],
        [ 3.0000,  0.0000],
        [18.0000,  0.0000],
        [ 4.0000,  0.0000],
        [ 5.0000,  0.0000],
        [17.0000,  0.0000],
        [ 6.0000,  0.0000],
        [16.0000,  0.0000],
        [15.0000,  0.0000],
        [14.0000,  0.0000],
        [ 7.0000,  0.0000],
        [ 8.0000,  0.0000],
        [ 9.0000,  0.0000],
        [13.0000,  0.0000],
        [12.0000,  0.0000],
        [10.0000,  0.0000],
        [11.0000,  0.0000]]),
eigenvectors=tensor([]))

3. Flops per second

In [59]:
from time import perf_counter
t0 = perf_counter()
M1 = torch.empty(5000, 5000).normal_()

t1 = perf_counter()
M2 = torch.empty(5000, 5000).normal_()

t2 = perf_counter()
M = torch.mm(M1, M2)
tf = perf_counter()
print('Time taken to generate two matrices is {}sec'.format(t2-t0))
print('Time taken to multiply two matrices is {}sec'.format(tf-t2))

Time taken to generate two matrices is 0.25444496599993727sec
Time taken to multiply two matrices is 1.9309690440004488sec


In [65]:
Flops_per_sec = 2*(5000**3)/(1e9*(tf-t2)) ##O(2m^3)
print('Floating point products have been executed per second is {} Gigaflops.'.format(Flops_per_sec))

Floating point products have been executed per second is 129.46867313940322 Gigaflops.


4. Playing with slides

Write a function mul˙row, using python loops (and not even slicing operators), that gets a 2d tensor
as argument, and returns a tensor of same size, whose first row is identical to the first row of the
argument tensor, the second row is multiplied by two, the third by three, etc.

In [136]:
def mul_row(m):
    row_num  = m.shape[0]
    col_num = m.shape[1]
    N = torch.empty((row_num, col_num)) 
    
    t0 = perf_counter()    
    for i in range(row_num):

        N[i]= (i+1) * m[i]
#         print(i)
    tf = perf_counter()
    print('Time1:', (tf-t0))
    return N

In [137]:
m = torch.full((1000, 400), 2.0)
mul_row(m)

Time1: 0.01668564500141656


tensor([[   2.,    2.,    2.,  ...,    2.,    2.,    2.],
        [   4.,    4.,    4.,  ...,    4.,    4.,    4.],
        [   6.,    6.,    6.,  ...,    6.,    6.,    6.],
        ...,
        [1996., 1996., 1996.,  ..., 1996., 1996., 1996.],
        [1998., 1998., 1998.,  ..., 1998., 1998., 1998.],
        [2000., 2000., 2000.,  ..., 2000., 2000., 2000.]])

In [138]:
def mul_row_fast(m):
    row_num  = m.shape[0]
    col_num = m.shape[1]
    
    t0 = perf_counter() 
    vect = torch.arange(1,row_num+1).reshape(row_num,1)
    N = m * vect
    tf = perf_counter()    
    print('Time2:', (tf-t0))    
    return N

In [139]:
mul_row_fast(m)

Time2: 0.0008365700014110189


tensor([[   2.,    2.,    2.,  ...,    2.,    2.,    2.],
        [   4.,    4.,    4.,  ...,    4.,    4.,    4.],
        [   6.,    6.,    6.,  ...,    6.,    6.,    6.],
        ...,
        [1996., 1996., 1996.,  ..., 1996., 1996., 1996.],
        [1998., 1998., 1998.,  ..., 1998., 1998., 1998.],
        [2000., 2000., 2000.,  ..., 2000., 2000., 2000.]])

In [145]:
print('The time ratio between running time while using loop and broadcasting is ', 0.01668564500141656/0.0008365700014110189)

The time ratio between running time while using loop and broadcasting is  19.945306397878667


Using loop take more time,approximately 20 times than the time of using broadcasting.