In [2]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch
import numpy as np

In [4]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [5]:
x = torch.tensor(4)####declaraling a scalar
x

tensor(4)

In [6]:
x.shape, x.dtype, x.size()

(torch.Size([]), torch.int64, torch.Size([]))

In [7]:
xx = torch.Tensor([4]) ####declaraling a tensor of one element
xx

tensor([4.])

In [8]:
xx.shape, xx.dtype, xx.type(), xx.size()

(torch.Size([1]), torch.float32, 'torch.FloatTensor', torch.Size([1]))

In [9]:
y = torch.Tensor(5) ##### it prints the random number 
y

tensor([0.0000e+00, 8.7126e-04, 1.8754e+28, 8.0439e+20, 4.1302e-08])

In [10]:
torch.tensor([2,3])

tensor([2, 3])

In [11]:
torch.rand(2,3)

tensor([[0.2119, 0.4147, 0.8303],
        [0.9378, 0.4227, 0.3007]])

In [12]:
yy = torch.zeros(2,3) ###zeros matrix

In [13]:
yy.fill_(5) ###fill the zeros matrix with a sppecific number

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [14]:
torch.ones(2,3) ##ones matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.randn(2,3)

tensor([[ 0.2614, -0.6211, -0.5258],
        [-0.6414,  0.4718, -1.8828]])

In [16]:
t = torch.Tensor(2,3,4)
type(t)

torch.Tensor

In [17]:
t

tensor([[[ 2.1019e-44,  4.6566e-10,  0.0000e+00,  4.6566e-10],
         [ 1.9618e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.1704e-41,  0.0000e+00,  2.2369e+08]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [        nan,         nan, -3.8711e+23,         nan],
         [ 2.2369e+08,  2.2369e+08,  0.0000e+00,  7.3468e-40]]])

In [18]:
tt = torch.Tensor([2,3,4])
tt

tensor([2., 3., 4.])

In [19]:
p = t.random_(10)  ##### the underscore means inplace
p

tensor([[[3., 4., 7., 2.],
         [8., 6., 4., 6.],
         [6., 3., 4., 5.]],

        [[4., 1., 3., 2.],
         [4., 1., 4., 6.],
         [2., 0., 7., 9.]]])

In [20]:
p.sqrt()

tensor([[[1.7321, 2.0000, 2.6458, 1.4142],
         [2.8284, 2.4495, 2.0000, 2.4495],
         [2.4495, 1.7321, 2.0000, 2.2361]],

        [[2.0000, 1.0000, 1.7321, 1.4142],
         [2.0000, 1.0000, 2.0000, 2.4495],
         [1.4142, 0.0000, 2.6458, 3.0000]]])

In [21]:
k = torch.Tensor(p)
k.resize_(3,8)

tensor([[3., 4., 7., 2., 8., 6., 4., 6.],
        [6., 3., 4., 5., 4., 1., 3., 2.],
        [4., 1., 4., 6., 2., 0., 7., 9.]])

In [22]:
v = torch.Tensor([1, 2, 4])
v.dim(), v.size()[0]

(1, 3)

In [23]:
v

tensor([1., 2., 4.])

In [24]:
v[0]

tensor(1.)

Matrices

In [25]:
m = torch.Tensor([[1,2,3,4],[5,6,7,8]])
m

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [26]:
m.size(), m.size(0), m.size(1)

(torch.Size([2, 4]), 2, 4)

In [27]:
m.numel() ## Total number of all elements of matrix

8

In [28]:
m_transpose = m.t()
m_transpose

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])

In [29]:
m.transpose(0,1)

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])

In [30]:
m.transpose(1,0)

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])

In [31]:
#convert numpy array to tensor
npy = np.random.rand(2,3)
print(type(npy))
tn = torch.from_numpy(npy)
print(tn.dtype)

<class 'numpy.ndarray'>
torch.float64


In [32]:
#convert numpy array to tensor
pl = torch.Tensor(2)
print(pl)
npt = pl.numpy()
print(npt)

tensor([0.0000e+00, 4.6566e-10])
[0.000000e+00 4.656613e-10]


In [33]:
x = torch.arange(6)
x_ = x.view(2,3) ## Reshape
x_

tensor([[0, 1, 2],
        [3, 4, 5]])

In [34]:
torch.add(x,x)

tensor([ 0,  2,  4,  6,  8, 10])

In [35]:
b = torch.Tensor(4)
b.view(2,2)

tensor([[0.0000e+00, 4.6566e-10],
        [0.0000e+00, 4.6566e-10]])

In [36]:
b.squeeze(0)#### to remove dimension one

tensor([0.0000e+00, 4.6566e-10, 0.0000e+00, 4.6566e-10])

Exercise1

In [37]:
d = torch.Tensor(3,3)

dd=d.unsqueeze(0) # adding one dimension
print(dd.dim())

3


Exercise2

In [38]:
d1 = dd.squeeze(0) # removing one dimension
print(d1.dim())

2


Exercise3

In [39]:
r = 3 + torch.rand(5,3)* 4 ## interval [3,7)
r

tensor([[6.2987, 3.9809, 6.8822],
        [5.9898, 6.3851, 5.1439],
        [4.5017, 6.4194, 6.6044],
        [4.7360, 6.2154, 4.6837],
        [5.2990, 6.7343, 3.7526]])

In [40]:
torch.Tensor(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Exercise4

In [41]:
n = torch.randn(5,3)
n
k = torch.rand(5,3).normal_(mean=0, std=1)### normal distribution

In [42]:
k

tensor([[-0.6140,  0.0260, -0.3653],
        [-0.3581,  0.5683,  0.4282],
        [ 0.3618,  0.6230, -0.5014],
        [-0.5653, -1.9850,  0.1102],
        [-0.3280,  0.3436,  2.2233]])

Exercise5

In [43]:
l = torch.Tensor([1,1,1,0,1])
torch.nonzero(l)### removing all zeros

tensor([[0],
        [1],
        [2],
        [4]])

Matrix multiplication(mm)

In [44]:
torch.mm(x1, x2)
x.mm(x1)

NameError: name 'x1' is not defined

Gradients

In [ ]:
x = torch.tensor([[2.0,3.0]], requires_grad=True)
z = 3 * x
print(z)

In [ ]:
loss = z.sum()

In [ ]:
loss.backward()###back propagation

In [ ]:
x.grad

Plotting

In [ ]:
import matplotlib.pyplot as plt
plt.hist(torch.randn(100**6).numpy(),10)

In [ ]:
x.data #### to access values of tensor

In [ ]:
torch.cuda.is_available()

Exercise 6

In [47]:
#### Tensor(3,1) and stack 4 copies together
t = torch.rand(3,1)
torch.hstack((t,t,t,t))

tensor([[0.2505, 0.2505, 0.2505, 0.2505],
        [0.6188, 0.6188, 0.6188, 0.6188],
        [0.4837, 0.4837, 0.4837, 0.4837]])

Exercise7

In [53]:
####batch matrix- matrix product of two 3D matrices
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
ab = torch.bmm(a, b)
print(ab.size())
ab

torch.Size([3, 4, 4])


tensor([[[1.7654, 0.9725, 1.5616, 1.3590],
         [1.5500, 0.7862, 1.1560, 1.2558],
         [2.3232, 1.1890, 1.5514, 1.7101],
         [1.9160, 1.0115, 1.2600, 1.5906]],

        [[1.3108, 1.2669, 0.7978, 0.6925],
         [1.1460, 0.8765, 1.1406, 1.2579],
         [1.1970, 1.0737, 0.8809, 0.8822],
         [1.1908, 1.2368, 1.1614, 1.1707]],

        [[0.8078, 1.8651, 1.1973, 1.6851],
         [1.0711, 1.0760, 1.0965, 1.1704],
         [0.3027, 1.1613, 0.8469, 1.2308],
         [1.2954, 1.9709, 1.4798, 1.6012]]])

In [49]:
# torch.bmm(a,b)

Exercise8

In [45]:
####batch matrix- matrix product of two 3D matrix and 2D matrix
a1 = torch.rand(3,4,5)
b1 = torch.rand(5,4)
ab_ = torch.matmul(a1, b1)
ab_

tensor([[[1.3454, 0.8637, 0.7933, 1.1036],
         [1.8642, 1.4145, 0.9157, 1.5543],
         [1.4705, 1.0578, 0.9769, 1.3746],
         [1.5884, 1.2481, 0.8678, 1.4166]],

        [[0.5522, 0.8477, 0.5358, 1.0917],
         [1.4324, 1.0405, 0.6089, 1.1810],
         [1.0298, 1.1886, 0.6531, 1.4304],
         [1.5483, 1.4789, 0.7523, 1.6248]],

        [[0.8387, 1.0973, 0.5504, 1.2895],
         [1.1403, 1.2522, 0.6119, 1.4295],
         [0.9329, 0.8882, 0.4960, 1.0246],
         [1.2451, 1.1150, 0.5510, 1.3711]]])

In [58]:

# b1.expand()